---

- hosts: localhost

  vars:
    dev_tools:
#      - docker
#      - git
#      - node
#      - npm
      - wget

  tasks:
    - name: Check Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew If not Present
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: brew_installed.stat.exists == false

    - name: Install libraries/utils with homebrew
      homebrew: name={{ item }} state=present
      with_items: dev_tools

    - name: Cleanup after brewing
      shell: brew cleanup
