---


- name: Install Nginx
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - nginx
    - frontend
    - deps