---

- name: Check if nginx is installed
  command: bash -lc "nginx -v"
  become: true
  register: nginx_status
  ignore_errors: true

- name: Prepare | Ubuntu Update apt-get
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"

- name: Prepare | Ubuntu Update apt-get | Check Cache
  stat: path=/var/cache/apt
  register: apt_cache_stat
  when: ansible_os_family == "Debian"

- name: Install Nginx on Ubuntu
  apt: pkg={{ item }} state=installed
  with_items:
      - nginx
      - curl
  when: ansible_os_family == "Debian"

- name: Create folders
  file: path=/etc/nginx/{{ item }} state=directory
  with_items:
    - sites-enabled
    - sites-available
  become: true
  when: nginx_status|failed
